version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: eshop-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      retries: 3

  app:
    build: .
    container_name: eshop-app
    ports:
      - "8501:8501"
    environment:
      MONGO_URI: "mongodb://admin:password@eshop-mongodb:27017/eshop?authSource=admin"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  mongodb_data:
