version: '3.8'

services:
  mongodb:
    image: mongo:6.0.8
    container_name: eshop-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: eshop
      TZ: America/Sao_Paulo
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    restart: unless-stopped
    networks:
      - eshop-network

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: eshop-app
    ports:
      - "8501:8501"
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: "mongodb://admin:password@eshop-mongodb:27017/eshop?authSource=admin&retryWrites=true&w=majority"
      PYTHONUNBUFFERED: 1
      STREAMLIT_SERVER_PORT: 8501
      STREAMLIT_SERVER_ADDRESS: 0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - eshop-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_data:
    driver: local

networks:
  eshop-network:
    driver: bridge
    name: eshop-network
